import Head from 'next/head'
export const HeadTsx = () => (
  <Head>
    <title>Mini Chat V.1.0</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)
